let products = [
    {
        name: 'Iphone 7 Plus',
        brand: 'Apple',
        price: '4.950.000 vnd',
        color: 'Black',
        specs: {
            CPU: 'Apple A11 Bionic 6 multiply',
            camera: 'Camera trước 7MP, camera sau 12MP',
            internal_memory: '64Gb',
            screen_type: 'LED-backlit IPS LCD, 4.7", Retina HD',
            screen_size: '5.2 inches',
            Screen_resolution: '2436 x 1125 pixels',
            Operating_system: 'IOS 11',
        }
    },
    {
        name: 'Iphone 7 Plus',
        brand: 'Apple',
        price: '4.950.000 vnd',
        color: 'Silver',
        specs: {
            CPU: 'Apple A11 Bionic 6 multiply',
            camera: 'Camera trước 7MP, camera sau 12MP',
            internal_memory: '64Gb',
            screen_type: 'LED-backlit IPS LCD, 4.7", Retina HD',
            screen_size: '5.2 inches',
            Screen_resolution: '2436 x 1125 pixels',
            Operating_system: 'IOS 11',
        }
    },
    {
        name: 'Iphone 8 ',
        brand: 'Apple',
        price: '5.550.000 vnd',
        color: 'Silver',
        specs: {
            CPU: 'Apple A11 Bionic 6 multiply',
            camera: 'Camera trước 7MP, camera sau 12MP',
            internal_memory: '64Gb',
            screen_type: 'LED-backlit IPS LCD, 4.7", Retina HD',
            screen_size: '5.2 inches',
            Screen_resolution: '2436 x 1125 pixels',
            Operating_system: 'IOS 11',
        }
    },
    {
        name: 'Iphone 8 ',
        brand: 'Apple',
        price: '5.550.000 vnd',
        color: 'Black',
        specs: {
            CPU: 'Apple A11 Bionic 6 multiply',
            camera: 'Camera trước 7MP, camera sau 12MP',
            internal_memory: '64Gb',
            screen_type: 'LED-backlit IPS LCD, 4.7", Retina HD',
            screen_size: '5.2 inches',
            Screen_resolution: '2436 x 1125 pixels',
            Operating_system: 'IOS 11',
        }
    },
    {
        name: 'Iphone 8 Plus',
        brand: 'Apple',
        price: '7.550.000 vnd',
        color: 'Silver',
        specs: {
            CPU: 'Apple A11 Bionic APL1W72',
            camera: 'Camera trước 7MP, camera sau 12MP',
            internal_memory: '64Gb',
            screen_type: 'Super Retina XDR',
            screen_size: '5.8 inches',
            Screen_resolution: '2436 x 1125 pixels',
            Operating_system: 'IOS 11',
        }
    },
    {
        name: 'Iphone 8 Plus',
        brand: 'Apple',
        price: '7.550.000 vnd',
        color: 'Rose gold',
        specs: {
            CPU: 'Apple A11 Bionic APL1W72',
            camera: 'Camera trước 7MP, camera sau 12MP',
            internal_memory: '64Gb',
            screen_type: 'Super Retina XDR',
            screen_size: '5.8 inches',
            Screen_resolution: '2436 x 1125 pixels',
            Operating_system: 'IOS 11',
        }
    },
    {
        name: 'Iphone 8 Plus',
        brand: 'Apple',
        price: '7.550.000 vnd',
        color: 'Red',
        specs: {
            CPU: 'Apple A11 Bionic APL1W72',
            camera: 'Camera trước 7MP, camera sau 12MP',
            internal_memory: '64Gb',
            screen_type: 'Super Retina XDR',
            screen_size: '5.8 inches',
            Screen_resolution: '2436 x 1125 pixels',
            Operating_system: 'IOS 11',
        }
    },
    {
        name: 'Iphone X',
        brand: 'Apple',
        price: '9.350.000 vnd',
        color: 'Black',
        specs: {
            CPU: '2x 2.1 GHz Monsoon , 4x 2.1 GHz Mistral',
            camera: '2x 12 MP, f/1.8 & f/2.4, tự động lấy nét nhận diện theo giai đoạn, 2x zoom quang học, OIS, 4 LED flash (2 tone)',
            internal_memory: '64Gb',
            screen_type: 'Cảm ứng điện dung OLED, 16 triệu màu',
            screen_size: '4.8 inches',
            Operating_system: 'IOS 11.1',
        }
    },
    {
        name: 'Iphone X',
        brand: 'Apple',
        price: '9.350.000 vnd',
        color: 'Silver',
        specs: {
            CPU: '2x 2.1 GHz Monsoon , 4x 2.1 GHz Mistral',
            camera: '2x 12 MP, f/1.8 & f/2.4, tự động lấy nét nhận diện theo giai đoạn, 2x zoom quang học, OIS, 4 LED flash (2 tone)',
            internal_memory: '64Gb',
            screen_type: 'Cảm ứng điện dung OLED, 16 triệu màu',
            screen_size: '4.8 inches',
            Operating_system: 'IOS 11.1',
        }
    },
    {
        name: 'Iphone 11',
        brand: 'Apple',
        version: 64,
        price: '21.990.000 vnd',
        color: 'Silver',
        specs: {
            screen: 6.1,
            screen_type: 'IPS lcd',
            os: 'IOS 13',
            main_camera: '12 mp',
            fron_camera: '12 mp',
            cpu: 'apple a13 bionic 6 core',
            ram: '4 gb',
            rom: '64 gb',
            battery: '3110 mAh',
            sim: '1 esim & 1 nano sim',
        }
    },
    {
        name: 'Iphone 11',
        brand: 'Apple',
        version: 64,
        price: '21.990.000 vnd',
        color: 'Green',
        specs: {
            screen: 6.1,
            screen_type: 'IPS lcd',
            os: 'IOS 13',
            main_camera: '12 mp',
            fron_camera: '12 mp',
            cpu: 'apple a13 bionic 6 core',
            ram: '4 gb',
            rom: '64 gb',
            battery: '3110 mAh',
            sim: '1 esim & 1 nano sim',
        }
    },

    {
        name: 'Iphone 11 Pro',
        brand: 'Apple',
        version: 64,
        price: '21.990.000 vnd',
        color: 'Silver',
        specs: {
            screen: 6.1,
            screen_type: 'IPS lcd',
            os: 'IOS 13',
            main_camera: '12 mp',
            fron_camera: '12 mp',
            cpu: 'apple a13 bionic 6 core',
            ram: '4 gb',
            rom: '64 gb',
            battery: '3110 mAh',
            sim: '1 esim & 1 nano sim',
        }
    },
    {
        name: 'Iphone 11 Pro',
        brand: 'Apple',
        version: 64,
        price: '21.990.000 vnd',
        color: 'Black',
        specs: {
            screen: 6.1,
            screen_type: 'IPS lcd',
            os: 'IOS 13',
            main_camera: '12 mp',
            fron_camera: '12 mp',
            cpu: 'apple a13 bionic 6 core',
            ram: '4 gb',
            rom: '64 gb',
            battery: '3110 mAh',
            sim: '1 esim & 1 nano sim',
        }
    },
    {
        name: 'Samsung Galaxy J7 Pro',
        brand: 'Samsung',
        price: '4.500.000 vnd',
        color: 'Black',
        specs: {
            screen_type: 'Super AMOLED, 5.5, Full HD',
            camera: '13MP : 13MP',
            Ram: '3GB',
            Operating_system: 'Android 7.0',
            Pin: 'Li-lon 3600 mAh',
            internal_memory: 'MicroSD, 256GB',
        }
    },
    {
        name: 'Samsung Galaxy J7 Pro',
        brand: 'Samsung',
        price: '4.500.000 vnd',
        color: 'Rose',
        specs: {
            screen_type: 'Super AMOLED, 5.5, Full HD',
            camera: '13MP : 13MP',
            Ram: '3GB',
            Operating_system: 'Android 7.0',
            Pin: 'Li-lon 3600 mAh',
            internal_memory: 'MicroSD, 256GB',
        }
    },
    {
        name: 'Samsung Galaxy note 9',
        brand: 'Samsung',
        price: '6.550.000 vnd',
        color: 'Green dark',
        specs: {
            screen_type: 'Super AMOLED, 16M color',
            camera: '12MP + 12MP, LED flash ',
            Ram: '8GB',
            Operating_system: 'Android OS, v8.1',
            Pin: 'Li-lon 4000 mAh',
            internal_memory: '512GB',
        }
    },
    {
        name: 'Samsung Galaxy note 9',
        brand: 'Samsung',
        price: '6.550.000 vnd',
        color: 'Rose',
        specs: {
            screen_type: 'Super AMOLED, 16M color',
            camera: '12MP + 12MP, LED flash ',
            Ram: '8GB',
            Operating_system: 'Android OS, v8.1',
            Pin: 'Li-lon 4000 mAh',
            internal_memory: '512GB',
        }
    },
    {
        name: 'Samsung Galaxy S10',
        brand: 'Samsung',
        price: '8.150.000 vnd',
        color: 'Silver green',
        specs: {
            screen_type: 'Dynamic AMOLED, 6.7, Quad HD + (2k+)',
            camera: '12MP + 12MP, LED flash ',
            Ram: '8GB',
            Operating_system: 'Android 9.0(Pie)',
            Pin: 'Li-lon 4500 mAh',
            internal_memory: '512GB',
        }
    },
    {
        name: 'Samsung Galaxy S10',
        brand: 'Samsung',
        price: '8.150.000 vnd',
        color: 'Cu-95',
        specs: {
            screen_type: 'Dynamic AMOLED, 6.7, Quad HD + (2k+)',
            camera: '12MP + 12MP, LED flash ',
            Ram: '8GB',
            Operating_system: 'Android 9.0(Pie)',
            Pin: 'Li-lon 4500 mAh',
            internal_memory: '512GB',
        }
    },
    {
        name: 'Samsung Galaxy A71',
        brand: 'Samsung',
        price: '9.490.000 vnd',
        color: 'Cu-95',
        specs: {
            screen_type: 'Dynamic AMOLED, 6.7, Full HD',
            camera: '32MP + 64MP',
            Ram: '8GB',
            Operating_system: 'Android 10.0',
            Pin: ' 4500 mAh',
            internal_memory: '128GB',
        }
    },
    {
        name: 'Samsung Galaxy A71',
        brand: 'Samsung',
        price: '9.490.000 vnd',
        color: 'Black',
        specs: {
            screen_type: 'Dynamic AMOLED, 6.7, Full HD',
            camera: '32MP + 64MP',
            Ram: '8GB',
            Operating_system: 'Android 10.0',
            Pin: ' 4500 mAh',
            internal_memory: '128GB',
        }
    },
      {
        name: 'OPPO Reno4',
        brand: 'OPPO',
        price: '8.490.000 vnd',
        color: 'Blue',
        specs: {
            weight: '165g',
            screen_type: 'AMOLED, 60GHz, Full HD',
            screen: '6.4 inches',
            camera: '32MP + 48MP',
            Ram: '8GB',
            Operating_system: 'Android',
            Pin: ' 4015 mAh, Fast charging 30W',
            internal_memory: '128GB',
        }
    },
    {
        name: 'OPPO Reno4',
        brand: 'OPPO',
        price: '8.490.000 vnd',
        color: 'Black',
        specs: {
            weight: '165g',
            screen_type: 'AMOLED, 60GHz, Full HD',
            screen: '6.4 inches',
            camera: '32MP + 48MP',
            Ram: '8GB',
            Operating_system: 'Android',
            Pin: ' 4015 mAh, Fast charging 30W',
            internal_memory: '128GB',
        }
    },
    {
        name: 'OPPO A92s',
        brand: 'OPPO',
        price: '7.290.000 vnd',
        color: 'Silver',
        specs: {
            CPU: 'Dimensity 800 5G (7nm)',
            weight: '165g',
            screen_type: 'AMOLED, 60GHz, Full HD',
            screen: '6.4 inches',
            camera: '32MP + 48MP',
            Ram: '8GB',
            Operating_system: 'Android 10.0, ColorOS 7',
            Pin: ' 4000 mAh, Fast charging 20W',
            internal_memory: '128GB',
        }
    },
    {
        name: 'OPPO A92s',
        brand: 'OPPO',
        price: '7.290.000 vnd',
        color: 'Blue Black',
        specs: {
            CPU: 'Dimensity 800 5G (7nm)',
            weight: '165g',
            screen_type: 'AMOLED, 60GHz, Full HD',
            screen: '6.4 inches',
            camera: '32MP + 48MP',
            Ram: '8GB',
            Operating_system: 'Android 10.0, ColorOS 7',
            Pin: ' 4000 mAh, Fast charging 20W',
            internal_memory: '128GB',
        }
    },
    {
        name: 'OPPO F15',
        brand: 'OPPO',
        price: '6.490.000 vnd',
        color: 'Blue',
        specs: {
            CPU: 'Mediatek Helio P70 (12nm)',
            weight: '165g',
            screen_type: 'AMOLED, 6.4, Full HD',
            screen: '6.4 inches',
            camera: '16MP + 48MP',
            Ram: '8GB',
            Operating_system: 'Android 10.0, ColorOS 7',
            Pin: ' 4025 mAh, Fast charging 20W',
            internal_memory: '128GB',
        }
    },
    {
        name: 'OPPO F15',
        brand: 'OPPO',
        price: '6.490.000 vnd',
        color: 'White',
        specs: {
            CPU: 'Mediatek Helio P70 (12nm)',
            weight: '165g',
            screen_type: 'AMOLED, 6.4, Full HD',
            screen: '6.4 inches',
            camera: '16MP + 48MP',
            Ram: '8GB',
            Operating_system: 'Android 10.0, ColorOS 7',
            Pin: ' 4025 mAh, Fast charging 20W',
            internal_memory: '128GB',
        }
    },
    {
    name: 'OPPO Find X2',
    brand: 'OPPO',
    price: '17.490.000 vnd',
    color: 'White',
    specs: {
        CPU: '8 nhan, 64-bit',
        weight: '196g',
        screen_type: 'AMOLED',
        screen: '6.7 inches',
        camera: '32MP + 48MP',
        Ram: '12GB',
        Operating_system: 'Android',
        Pin: ' 4200 mAh, Fast charging 20W',
        internal_memory: '256GB',
    }
    },
    {
    name: 'OPPO Find X2',
    brand: 'OPPO',
    price: '17.490.000 vnd',
    color: 'Black',
    specs: {
        CPU: '8 nhan, 64-bit',
        weight: '196g',
        screen_type: 'AMOLED',
        screen: '6.7 inches',
        camera: '32MP + 48MP',
        Ram: '12GB',
        Operating_system: 'Android',
        Pin: ' 4200 mAh, Fast charging 20W',
        internal_memory: '256GB',
    }
    },

    {
        name: 'Xiaomi Redmi Note 9 Pro',
        brand: 'Xiaomi',
        price: '6.990.000 vnd',
        color: 'Black',
        specs: {
            CPU: 'Snapdragon 720G',
            weight: '196g',
            screen_type: 'IPSLCD, 6.67, Full HD',
            screen: '6.4 inches',
            camera: '32MP + 48MP',
            Ram: '6GB',
            Operating_system: 'Android 10',
            Pin: '5020 mAh, Fast charging 20W',
            internal_memory: '128GB',
        }
    },
        {
            name: 'Xiaomi Redmi Note 9 Pro',
            brand: 'Xiaomi',
            price: '6.990.000 vnd',
            color: 'Silver',
            specs: {
                CPU: 'Snapdragon 720G',
                weight: '196g',
                screen_type: 'IPSLCD, 6.67, Full HD',
                screen: '6.4 inches',
                camera: '32MP + 48MP',
                Ram: '6GB',
                Operating_system: 'Android 10',
                Pin: '5020 mAh, Fast charging 20W',
                internal_memory: '128GB',
            }
    },
         {
            name: 'Xiaomi Mi Note 10',
            brand: 'Xiaomi',
            price: '10.590.000 vnd',
            color: 'Silver',
            specs: {
                CPU: 'Snapdragon 720G',
                weight: '196g',
                screen_type: 'IPSLCD, 6.67, Full HD',
                screen: '6.47 inches',
                camera: '32MP + 48MP',
                Ram: '6GB',
                Operating_system: 'Android 10',
                Pin: '5260 mAh battery, Fast charging 20W',
                internal_memory: '128GB',
            }
    },
         {
            name: 'Xiaomi Mi Note 10',
            brand: 'Xiaomi',
            price: '10.590.000 vnd',
            color: 'Black',
            specs: {
                CPU: 'Snapdragon 720G',
                weight: '196g',
                screen_type: 'IPSLCD, 6.67, Full HD',
                screen: '6.47 inches',
                camera: '32MP + 48MP',
                Ram: '6GB',
                Operating_system: 'Android 10',
                Pin: '5260 mAh battery, Fast charging 20W',
                internal_memory: '128GB',
            }
     },
         {
            name: 'Xiaomi Mi POCO X3  ',
            brand: 'Xiaomi',
            price: '16.890.000 vnd',
            color: 'Blue Glacier',
            specs: {
                CPU: 'Qualcomm SM8250 Snapdragon 865 (7 nm+)',
                weight: '196g',
                screen_type: 'IPSLCD, 6.67, Full HD',
                screen: '6.67 inches',
                camera: '20MP + 108MP',
                Ram: '8GB',
                Operating_system: 'Android 10',
                Pin: '4500 mAh battery, Fast charging 20W',
                internal_memory: '256GB',
            }
    },
         {
            name: 'Xiaomi Mi POCO X3  ',
            brand: 'Xiaomi',
            price: '16.890.000 vnd',
            color: 'White',
            specs: {
                CPU: 'Qualcomm SM8250 Snapdragon 865 (7 nm+)',
                weight: '196g',
                screen_type: 'IPSLCD, 6.67, Full HD',
                screen: '6.67 inches',
                camera: '20MP + 108MP',
                Ram: '8GB',
                Operating_system: 'Android 10',
                Pin: '4500 mAh battery, Fast charging 20W',
                internal_memory: '256GB',
            }
    },
    {
        name: 'Xiaomi Mi MAX 3 ',
        brand: 'Xiaomi',
        price: '5.890.000 vnd',
        color: 'Blue Glacier',
        specs: {
            CPU: 'Qualcomm SDM636',
            weight: '196g',
            screen_type: 'IPSLCD, 6.67, Full HD',
            screen: '6.67 inches',
            camera: '8.0MP + 12MP',
            Ram: '4GB',
            Operating_system: 'Android 10',
            Pin: 'Non-removeable Li-on 5500 mAh battery',
            internal_memory: '64GB',
        }
     },
     {
        name: 'Xiaomi Mi MAX 3 ',
        brand: 'Xiaomi',
        price: '5.890.000 vnd',
        color: 'Black',
        specs: {
            CPU: 'Qualcomm SDM636',
            weight: '196g',
            screen_type: 'IPSLCD, 6.67, Full HD',
            screen: '6.67 inches',
            camera: '8.0MP + 12MP',
            Ram: '4GB',
            Operating_system: 'Android 10',
            Pin: 'Non-removeable Li-on 5500 mAh battery',
            internal_memory: '64GB',
        }
     },

]